---
# tasks file start_vm
- set_fact: vm_memory_g="{{ vm_memory }}GiB"

- name: Start VM
  ovirt_vm:
    auth: "{{ ovirt_auth }}"
    name: "{{ rhvm_vm_name }}"
    host: "{{ rhvm_sat_host }}"
    high_availability: no
    state: running
    timeout: 1800
    wait: yes
