---
# tasks file for deploy_vm
- name: Create and run VM from template
  ovirt_vm:
    auth: "{{ ovirt_auth }}"
    name: "{{ rhvm_vm_name }}"
    template: "{{ rhvm_template }}"
    cluster: "{{ rhvm_cluster }}"
    memory: "{{ vm_memory }}"
    host: "{{ rhvm_sat_host }}"
    high_availability: no
    state: running
    wait: yes
    cloud_init_persist: yes
    cloud_init:
      custom_script: |
        preserve_hostname: false
        hostname: "{{ rhvm_vm_name }}"
        fqdn: "{{ rhvm_vm_name }}"
