---
# tasks file for hl_ovirt
- name: Create and run VM from template
  ovirt_vm:
    auth: "{{ ovirt_auth }}"
    name: "{{ rhvm_vm_name }}"
    template: "{{ rhvm_template }}"
    cluster: "{{ cluster }}"
    memory: "{{ vm_memory }}"
    host: "{{ rhvm_sat_host }}"
    high_availability: no
    state: running
    wait: yes
    cloud_init_persist: yes
    cloud_init:
      host_name: "{{ rhvm_vm_name }}"
      user_name: root
      root_password: "{{ rhvm_password }}"
...
