---
# tasks file for set_powermgmt.yml
- name: Set Power Managemtn Agent for RHEV host
  become: false
  ovirt_host_pm:
    auth: "{{ ovirt_auth }}"
    name: "{{ rhvm_sat_host }}"
    address: "{{ rhvm_bmc_ip }}"
    username: "{{ bmc_user }}"
    password: "{{ bmc_password }}"
    type: ilo4
- ovirt_host:
    auth: "{{ ovirt_auth }}"
    name: "{{ rhvm_sat_host }}"
    cluster: "{{ rhvm_cluster }}"
    address: "{{ rhvm_sat_host }}"
    password: "{{ rhvm_password }}"
    override_iptables: true
    power_management_enabled: yes
    kdump_integration: disabled
    wait: yes
...
