---
# tasks file for set_passthrough
- name: Set passthrough (intel_iommu=on)
  become: false
  ovirt_host:
    auth: "{{ ovirt_auth }}"
    name: "{{ rhvm_sat_host }}"
    cluster: "{{ rhvm_cluster }}"
    address: "{{ rhvm_sat_host }}"
    password: "{{ rhvm_password }}"
    override_iptables: true
    state: restarted
    wait: yes

