---
  - name: Copy generate_gaudi_addresses.sh to target
    copy:
      src: /habana-labs/generate_gaudi_addresses.sh
      dest: /tmp/generate_gaudi_addresses.sh
      mode: 755    
  - name: Run the script generate_gaudi_addresses.sh
    script: /tmp/generate_gaudi_addresses.sh
    register: out
