---
# vars file for deploy_vm
rhvm_password: r3dh4t1!

datacenter: "{{ rhvm_fqdn }}"
cluster: Default
vm_memory: 1GiB
dns_server: 10.111.52.15

rhvm_fqdn: ovirtmanager.habana-labs.com
rhvm_user: admin@internal
rhvm_cafile: /etc/pki/ovirt-engine/ca.pem

rhvm_sat_host: 
rhvm_vm_name: 
rhvm_template: 
rhvm_root_password: 
