---
# tasks file for assign_gaudi
- set_fact: vm_memory_g="{{ vm_memory }}GiB"

#- debug:
#    msg: "vm_memory is {{ vm_memory_g }}"

- name: Assign Gaudi to VM
  ovirt_vm:
    auth: "{{ ovirt_auth }}"
    name: "{{ rhvm_vm_name }}"
    host_devices:
      - name: "{{ gaudi_slot }}"
        state: present
